import "./functions/hello.js";
import { AzureTableStorage } from "./shared/azure-table-storage.js";
import { BcryptPasswordHasher } from "./shared/bcrypt-password-hasher.js";
import { SystemClock } from "./shared/clock.js";
import { SystemRandom } from "./shared/random.js";
import { HmacSessionSigner } from "./shared/session-signer.js";
import { SystemLogger } from "./shared/logger.js";

import { registerLogin } from "./functions/login.js";
import { registerLogout } from "./functions/logout.js";
import { registerMe } from "./functions/me.js";
import { registerUsers } from "./functions/users.js";
import { registerUsersPublic } from "./functions/users-public.js";
import { registerUsersId } from "./functions/users-id.js";
import { registerYears } from "./functions/years.js";
import { registerYearsId } from "./functions/years-id.js";
import { registerCourses } from "./functions/courses.js";
import { registerCoursesId } from "./functions/courses-id.js";
import { registerCards } from "./functions/cards.js";
import { registerCardsId } from "./functions/cards-id.js";
import { registerSessions } from "./functions/sessions.js";
import { registerAttempts } from "./functions/attempts.js";
import { registerSessionsId } from "./functions/sessions-id.js";
import { registerStatsSession } from "./functions/stats-session.js";
import { registerStatsUser } from "./functions/stats-user.js";
import { registerStatsCourse } from "./functions/stats-course.js";
import { registerStatsFamily } from "./functions/stats-family.js";
import { registerStatsHeatmap } from "./functions/stats-heatmap.js";
import { registerStatsUpload } from "./functions/stats-upload.js";
import { registerCardsImport } from "./functions/cards-import.js";
import { registerCardsBatch } from "./functions/cards-batch.js";
import { registerCardsBulkDelete } from "./functions/cards-bulk-delete.js";
import { registerCardsReverse } from "./functions/cards-reverse.js";
import { registerCardsEnrich } from "./functions/cards-enrich.js";
import { registerLeaderboard } from "./functions/leaderboard.js";
import { registerExport } from "./functions/export.js";
import { createClaudeClient } from "./shared/claude.js";

const connectionString = process.env.AZURE_STORAGE_CONNECTION_STRING ?? "";
const anthropicApiKey = process.env.ANTHROPIC_API_KEY ?? "";
const sessionSecret = process.env.SESSION_SECRET ?? "";
const cookieSecure = process.env.COOKIE_SECURE !== "false";

const tables = new AzureTableStorage({ connectionString });
const hasher = new BcryptPasswordHasher();
const clock = new SystemClock();
const random = new SystemRandom();
const signer = new HmacSessionSigner({ secret: sessionSecret, clock });
const logger = new SystemLogger();

registerLogin({ tables, hasher, signer, clock, logger, cookieSecure });
registerLogout({ cookieSecure });
registerMe({ tables, signer });
registerUsers({ tables, signer, hasher, random, clock });
registerUsersPublic({ tables });
registerUsersId({ tables, signer, hasher });
registerYears({ tables, signer, random });
registerYearsId({ tables, signer });
registerCourses({ tables, signer, clock, random });
registerCoursesId({ tables, signer });
registerCards({ tables, signer, clock, random });
registerCardsId({ tables, signer, clock });
registerSessions({ tables, signer, clock, random });
registerAttempts({ tables, signer, clock, random });
registerSessionsId({ tables, signer, clock });
registerStatsSession({ tables, signer });
registerStatsUser({ tables, signer, clock });
registerStatsCourse({ tables, signer, clock });
registerStatsFamily({ tables, signer, clock });
registerStatsHeatmap({ tables, signer, clock });
registerStatsUpload({ tables, signer, clock });
const claude = createClaudeClient(anthropicApiKey);
if (anthropicApiKey.trim().length === 0) {
  logger.error("anthropic_api_key_missing");
}
registerCardsImport({ tables, signer, clock, claude, logger });
registerCardsBatch({ tables, signer, clock, random });
registerCardsBulkDelete({ tables, signer, clock });
registerCardsReverse({ tables, signer, clock, random });
registerCardsEnrich({ tables, signer, clock, claude });
registerLeaderboard({ tables, signer, clock });
registerExport({ tables, signer, clock });
